package com.tekion.accounting.fs.pdfPrinting.dto;

public enum PdfDocumentType {
  ISSUEDCHECK,
  CUSTOMER_STATEMENT,
  BATCH_CHECKS,
  BATCH_CHECKS_COPY,
  BATCH_PAYMENT_SUMMARY,
  CUSTOMER_SNAPSHOT,
  BATCH_EFTS,
  FINANCIAL_STATEMENT
}
